// Rewritten from https://github.com/ldbc/ldbc_snb_implementations/blob/dev/cypher/queries/interactive-short-1.cypher
FROM SNB
MATCH (n:Person)-[:IS_LOCATED_IN]->(p:Place)
WHERE n.id = "3"
RETURN n.firstName AS firstName,
  n.lastName AS lastName,
  n.birthday AS birthday,
  n.locationIP AS locationIP,
  n.browserUsed AS browserUsed,
  p.id AS cityId,
  n.gender AS gender,
  n.creationDate AS creationDate